.TH MXKBC 1 mxkbc
.SH NAME
mxkbc \- modular X key bind client \- client for mxkbd to add, list, remove, and set keybinds and keybind modes
.SH SYNOPSIS
.B mxkbc
.RI [ MXKBC_OPTIONS ]
.I OPERATION MODE_OPTION OPERATION_ARGS
.PP
.B mxkbc
.RI [ MXKBC_OPTIONS ]
.I OPERATION
k|keybind
.RI [ MODE_OPTION "] " OPERATION_ARGS
.SH DESCRIPTION
.B mxkbc
is a client for
.BR mxkbd .
This client is where one configures
.B mxkbd
through
.BR mxkbd 's
arguments.
.B mxkbd
must first be started before using
.BR mxkbc .
.SH MXKBC_OPTIONS
.TP
.BI \-s " SOCKET_FILE_PATH"
change the file that is to be used to communicated with
.B mxkbd
to
.IR SOCKET_FILE_PATH .
.SH OPERATIONS
.I OPERATION
is performed on keybinds if k or keybind is specified immediately after
.IR OPERATION .
Otherwise it is performed on modes. Valid values for
.I OPERATION
are as follows:
.PP
.BR l , list
.RS
.B list
out property of mode(s) or keybind(s) to standard output.
.RE
.PP
.BR a , add
.RS
.B add
a mode or keybind.
.RE
.PP
.BR r , remove
.RS
.B remove
a mode or keybind.
.RE
.PP
.BR s , set
.RS
.B set
property of a mode or keybind.
.RE
.SH MODE_OPTION
.I MODE_OPTION
specifies the mode to act on \- defaults to the selected mode (the mode indicated by the mode option
.IR -s ).
It is obligatory if
.I OPERATION
is not performed on keybinds. Otherwise it is only necessary if the mode to operate the keybind
.I OPERATION
on is not the mode set to be the selected mode. Valid values for the MODE_OPTION are the following:
.TP
.B \-g
.I OPERATION
is performed on the mode set to be the grabbed mode
.TP
.B \-d
.I OPERATION
is performed on the mode set to be the default mode
.TP
.B \-s
.I OPERATION
is performed on the mode set to be the selected mode
.TP
.B \-a
This is only applicable to the
.B list
operation when done
.BR "on modes" .
This will list out the value
of
.I PROPERTY
of for each and every mode (see below). With the
.B list
operation
.B on keybinds
this is a
.B list arg
(see below).
.PP
.BI \-m " MODE_NAME"
.PP
for
.I OPERATIONS
on keybinds and...
.PP
.BR m | mode
.I MODE_NAME
.PP
for
.I OPERATIONS
on modes
.PP
.RS
.I OPERATION
is performed on the mode that has
.I MODE_NAME
as its name
(mode.name == 
.IR MODE_NAME ).
Furthermore take note that this is the only acceptable
.I MODE_OPTION
for the
.B add
operation when done 
.B on
a
.BR mode .
.RE
.SH add args
.SS on mode
.RI [ DESCRIPTION ]
.PP
Take note that the only acceptable
.I MODE_OPTION
is
.PP
.BR m | mode
.I MODE_NAME
.PP
(thus full form
.PP
.B mxkbc
add m|mode
.I MODE_NAME
.RI [ DESCRIPTION ]
.PP
).
.SS on keybind
.IR "SEQ FILE_OR_COMMAND" " [" DESCRIPTION ]
.SH remove args
.SS on mode
No 
.I OPERATION_ARGS
are available. Only
.I MODE_OPTION
is applicable.
.SS on keybind
.I SEQ
.SH set args
.SS on mode
.BR \-g | \-s | \-d
.PP
.I PROPERTY VALUE
.SS on keybind
.I SEQ PROPERTY VALUE
.SH list args
.SS on mode(s)
.RI [ PROPERTY ]
.SS on keybind(s)
.B \-a
.RI [ PROPERTY ]
.PP
.IR SEQ " [" PROPERTY ]
.SH OPERATION_ARGS
.B SEQ
.RS
key sequence to trigger execution of
.IR FILE_OR_COMMAND .
Keys are seperated by +.
.RE
.B FILE_OR_COMMAND
.RS
file or command to execute upon pressing all the keys in
.I SEQ
in the order specified. If
.I FILE_OR_COMMAND
is set to \-
.RI ( FILE_OR_COMMAND
== "-") then
.I FILE_OR_COMMAND
is set to the content of standard input. Furthermore if standard input is not available it will be set in a manner similar to the
.B cat
command.
.RE
.B PROPERTY
.RS
property of keybind or mode to
.B set
to
.I VALUE
or
.BR list .
Valid values are the following:
.PP
.BR d , description
.RS
Description of what a keybind or mode does or is for.
.RE
.BR c , command
.RS
The command executed when the keys within
.I SEQ
are all pressed as specified. Only relevant for
.I OPERATIONS
performed
.BR "on keybind(s)" .
.RE
.BR n , name
.RS
The name of the mode of the current
.IR OPERATION .
Only relevant for
.I OPERATIONS
performed
.BR "on mode(s)" .
If a
.I PROPERTY
is not specified for the
.B list
operation then this will be the property whose
.I VALUE
is displayed.
.RE
.BR s , seq
.RS
The sequence of keys that need be pressed to trigger
.IR FILE_OR_COMMAND .
Only relevant for
.I OPERATIONS
performed
.BR "on keybind(s)" .
If a
.I PROPERTY
is not specified for the
.B list
operation then this will be the property whose
.I VALUE
is displayed.
.RE
.RE
.B VALUE
.RS
Value to set property of a keybind or mode specified by
.I PROPERTY
to.
.RE
.B DESCRIPTION
.RS
Description of what a keybind or mode does or is for.
.RE
.B \-g
.RS
Only applicable with the set operation when done
.B on
a
.BR mode .
Set the grabbed mode to this
.IR OPERATION 's
mode. Not to be confused with
.IR MODE_OPTION 's
.BR "\-g " option.
.RE
.B \-s
.RS
Only applicable with the set operation when done
.B on
a
.BR mode .
Set the selected mode to this
.IR OPERATION 's
mode. Not to be confused with
.IR MODE_OPTION 's
.BR "\-s " option.
.RE
.B \-d
.RS
Only applicable with the set operation when done
.B on
a
.BR mode .
Set the default mode to this
.IR OPERATION 's
mode. Not to be confused with
.IR MODE_OPTION 's
.BR "\-d " option.
.RE
.B \-a
.RS
This is only applicable to the
.B list
operation when done
.BR "on keybinds" .
This will list out the value
of
.I PROPERTY
of for each and every keybind of the
.B list
operation. With the
.B list
operation
.B on modes
this is a
.I MODE_OPTION
(see above).
.RE
.SH AUTHORS
Written by Zachary Schlitt <ztschlitt@gmail.com>
.SH LICENSE
GPL 3.0
